### ISSUE TITLE
请问有直播回放吗?

### ISSUE THREAD

**Issue by MrAMS** [ChunxuGuo/SummerSchool2022#1]
作者您好,感觉您写的讲义非常的清晰,请问您还有这次**Summer School 2022**的录播回放吗?如果方便的话给个链接,感谢您

**Comment by ChunxuGuo** [comment]
你好，MrAMS。这个没有官方release的版本，但是有同学录屏放在B站了：https://www.bilibili.com/video/BV1sR4y1f7P6    https://www.bilibili.com/video/BV1me4y1k7Hn

**Comment by MrAMS** [comment]
感谢您!
